### ISSUE TITLE
Was not a one-click install

### ISSUE THREAD

**Issue by scrublullz** [SparkITSolutions/phoenix#2]
I don't have the `/ssd` folder on my computer. What do I do?!?!?!?!?

**Comment by maynardflies** [comment]
Our installer has a section for your various inputs.  at https://github.com/SparkITSolutions/phoenix/blob/legacy/install/ubuntu_install.sh#L30 we list a few of the setups we have in our lab, one of which is where our VM storage was.  https://github.com/SparkITSolutions/phoenix/blob/legacy/install/ubuntu_install.sh#L120 is where, for example, you would put your own VM storage location.

**Comment by scrublullz** [comment]
This looks like half-written content that Joe Blow and one Fowler would be involved in.

/s :dancer:

**Comment by maynardflies** [comment]
Please read through Line 1-126 of https://github.com/SparkITSolutions/phoenix/blob/legacy/install/ubuntu_install.sh on your cloned repo and set the properties as you see fit.
