### ISSUE TITLE
VPN Profiles Not Prepared for Multiple Adapters

### ISSUE THREAD

**Issue by scrublullz** [SparkITSolutions/phoenix#3]
In `ubuntu_install.sh` on line 731, VPNARRAY is loaded with the interface names and it expects them to be distinct without mentioning modification previously.

`VPNARRAY=$(grep dev openvpn/*.conf|awk '{print $NF}'|tr '\n' ' '|sed 's/.$//g')`

Output of these commands on configs without unique `dev tun` is:  `tun tun tun tun tun tun tun tun tun tun tun tun tun tun...`

**Comment by maynardflies** [comment]
this may help resolve your issue

`cd openvpn_configs
C=1
ls *.conf|while read file; do
    sed -i "s/dev.*/dev tun$C/" $file
    C=$((C + 1))
done`

**Comment by scrublullz** [comment]
Darn you.  I came up with:
```
#!/bin/bash
TUNNEL=10
for f in openvpn/*.conf
do
  sed -i "s/dev tun/dev tun$TUNNEL/g" $f
  TUNNEL=`expr $TUNNEL + 1`
done
```
